name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - published
      
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget
  
defaults:
  run:
    shell: pwsh

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release /warnaserror
      
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal
      
  publish_nuget:
    needs: build
    if: github.event_name == 'release'
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pack
        run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }} -p:GeneratePackageOnBuild=false /p:PackageVersion=${{ github.ref_name }}

      - uses: actions/upload-artifact@v7
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NuGetDirectory }}/*.nupkg

      - name: Push to GitHub Packages
        run: dotnet nuget push ${{ env.NuGetDirectory }}/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate